### ISSUE TITLE
Auto-detect Mark II hardware

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-installer#10]
It would be nice to the installer to detect the Mycroft Mark II hardware in order to install the right Open Voice OS requirements and have a Mark II working out of the box.

**Comment by JarbasAl** [comment]
related https://github.com/OpenVoiceOS/ovos-i2csound

**Comment by goldyfruit** [comment]
https://github.com/OpenVoiceOS/ovos-installer/pull/63
