### ISSUE TITLE
Installer just closes after selecting options

### ISSUE THREAD

**Issue by Speshals** [OpenVoiceOS/ovos-installer#100]
### Discussed in https://github.com/orgs/OpenVoiceOS/discussions/272

<div type='discussions-op-text'>

<sup>Originally posted by **Speshals** June 22, 2024</sup>
Get to just after confirming options and then the installer closes with no error or log. 
This is what is in the console: ➤ Checking for existing instance... [done]
➤ Retrieving OS information... [done]
➤ Detecting AVX/SIMD support... [done]
➤ Checking for Raspberry Pi board... [done]
➤ Detecting sound server... [done]
➤ Detecting display server... [done]
➤ Validating installer package requirements... [done]
➤ Creating installer Python virtualenv... [done]
➤ Installing Ansible requirements in Python virtualenv... [done]
➤ Looking for automated scenario... [done]
➤ Scan I2C bus for hardware auto-detection...[done]</div>

**Comment by goldyfruit** [comment]
Please run the installer in `debug` mod and share the output.

```
sh -c "curl -s https://raw.githubusercontent.com/OpenVoiceOS/ovos-installer/main/installer.sh -o installer.sh && chmod +x installer.sh && sudo ./installer.sh -d && rm installer.sh"
```

**Comment by goldyfruit** [comment]
I'm not able to reproduce this issue on Raspberry Pi 5 with Raspberry Pi OS Bookworm 64-bit Lite.

**Comment by goldyfruit** [comment]
![image](https://github.com/OpenVoiceOS/ovos-installer/assets/614115/48a26095-472f-4e7b-8dff-d065147d8e9c)

Closing for now, feel free to re-open.
