### ISSUE TITLE
Error During Installation with installer.sh Script

### ISSUE THREAD

**Issue by Natrinicle** [OpenVoiceOS/ovos-installer#114]
Getting an error when attempting to use the installer script

[ovos-installer.log](https://github.com/user-attachments/files/16395367/ovos-installer.log)
https://dpaste.com/5YNYQJ9CU

```
fatal: [127.0.0.1]: FAILED! => {"msg": "The conditional check 'ansible_distribution_major_version is version('11', '>=')' failed. The error was: Version comparison failed: '<' not supported between instances of 'str' and 'int'\n\nThe error appears to be in '/home/natrinicle/ovos-installer/ansible/roles/ovos_hardware_mark1/tasks/prepare.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Add {{ ovos_installer_user }} to dialout group\n  ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes. Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}
```

**Comment by goldyfruit** [comment]
Hi @Natrinicle 

It seems you are using the Debian `testing` which is not supported, only versions `10`, `11` and `12` are.

**Comment by nrob81** [comment]
Hello, I have the same problem, and I am using debian testing. 
```
~ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux trixie/sid"
NAME="Debian GNU/Linux"
VERSION_CODENAME=trixie
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

```

**Comment by goldyfruit** [comment]
> Hello, I have the same problem, and I am using debian testing.
> 
> ```
> ~ cat /etc/os-release 
> PRETTY_NAME="Debian GNU/Linux trixie/sid"
> NAME="Debian GNU/Linux"
> VERSION_CODENAME=trixie
> ID=debian
> HOME_URL="https://www.debian.org/"
> SUPPORT_URL="https://www.debian.org/support"
> BUG_REPORT_URL="https://bugs.debian.org/"
> ```

Hi @nrob81 

Debian Trixtie is not supported by the installer as Debian Trixie is not considered as **stable** but **testing**.

See previous message from July 27th:

> Hi @Natrinicle
> 
> It seems you are using the Debian `testing` which is not supported, only _(stable)_ versions `10`, `11` and `12` are.
>
