### ISSUE TITLE
 OpenSuse Tumbleweed-Slowroll support

### ISSUE THREAD

**Issue by J-Kappes** [OpenVoiceOS/ovos-installer#118]
I tried the installer script on Slowroll and it isn't supported. Could "support" be added, assuming there are no actual issues with this?

**Comment by goldyfruit** [comment]
@J-Kappes thanks!

Could you please share `/etc/os-release`

**Comment by goldyfruit** [comment]
@J-Kappes I'm a bit confused since `slowroll` seems to have the same `ID` as `tumbleweed` from `/etc/os-release` which means that it should work.

**Comment by J-Kappes** [comment]
```
NAME="openSUSE Tumbleweed-Slowroll"
# VERSION="20240702"
ID="opensuse-slowroll"
ID_LIKE="opensuse suse"
VERSION_ID="20240702"
PRETTY_NAME="openSUSE Tumbleweed-Slowroll"
ANSI_COLOR="0;32"
# CPE 2.3 format, boo#1217921
CPE_NAME="cpe:2.3:o:opensuse:slowroll:20240702:*:*:*:*:*:*:*"
#CPE 2.2 format
#CPE_NAME="cpe:/o:opensuse:slowroll:20240702"
BUG_REPORT_URL="https://bugzilla.opensuse.org"
SUPPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org"
DOCUMENTATION_URL="https://en.opensuse.org/openSUSE:Slowroll"
LOGO="distributor-logo-Slowroll"
```
error:
```

➤ Checking for existing instance... [done]
➤ Retrieving OS information... [done]
➤ Detecting AVX/SIMD support... [done]
➤ Checking for Raspberry Pi board... [done]
➤ Detecting sound server... [done]
➤ Detecting display server... [done]
➤ Validating installer package requirements... [fail]
Operating system not supported.
```

**Comment by goldyfruit** [comment]
@J-Kappes Just pushed a commit, could you please try again?

**Comment by J-Kappes** [comment]
Actually, I selected container install and it didn't create any containers despite exiting successfully.

So I tried running the install script with the `--uninstall` flag but that produces the same result as without that flag.

**Comment by goldyfruit** [comment]
> Actually, I selected container install and it didn't create any containers despite exiting successfully.
> 
> So I tried running the install script with the `--uninstall` flag but that produces the same result as without that flag.

Could you please share the `/var/log/ovos-installer.log`?

**Comment by J-Kappes** [comment]
[ovos-installer.log](https://github.com/user-attachments/files/16455655/ovos-installer.log)

**Comment by goldyfruit** [comment]
> [ovos-installer.log](https://github.com/user-attachments/files/16455655/ovos-installer.log)

The playbook failed.

```
2024-08-01 13:47:20,566 p=33883 u=root n=ansible | TASK [ovos_installer : Add rj to pipewire group] ***************************************************************************************
2024-08-01 13:47:20,566 p=33883 u=root n=ansible | Thursday 01 August 2024  13:47:20 +0200 (0:00:00.331)       0:00:06.850 ******* 
2024-08-01 13:47:20,903 p=33883 u=root n=ansible | fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Group pipewire does not exist"}
```

But you mentioned the installer being exited successfully, are you sure about that?

**Comment by J-Kappes** [comment]
Yes, I got the message telling me OVOS is running and the exit code after that was 0.

**Comment by goldyfruit** [comment]
> Yes, I got the message telling me OVOS is running and the exit code after that was 0.

Are you able to reproduce this with the containers method?

**Comment by goldyfruit** [comment]
> > Yes, I got the message telling me OVOS is running and the exit code after that was 0.
> 
> Are you able to reproduce this with the containers method?

Found the issue and it should be fixed.

https://github.com/OpenVoiceOS/ovos-installer/commit/31c299e1f1ab34edba64ca8acab12b0bf23791ac

**Comment by J-Kappes** [comment]
Now it rightfully exited unsuccessfully and I could more easily find the error messages in the output.

I still had to manually add the pipewire group and install the xhost and docker-compose packages.

**Comment by goldyfruit** [comment]
> I still had to manually add the pipewire group and install the xhost and docker-compose packages.

Already open for `xhost` https://github.com/OpenVoiceOS/ovos-installer/issues/122

**Comment by goldyfruit** [comment]
@J-Kappes the `pipewire` issue is fixed.

**Comment by goldyfruit** [comment]
@J-Kappes the `xhost` issue if fixed too.

Thanks for testing and reporting! :+1:
