### ISSUE TITLE
Trouble with installer on Ubuntu 24.04

### ISSUE THREAD

**Issue by unstuckconsortium** [OpenVoiceOS/ovos-installer#130]
I'm trying to install OVOS on a new build Ubuntu Mate 24.04 (LTS) using the installer script.  I've tried it a couple of times and it stops in the same place each time.  I'm using the venv, as the How-To guide suggests this is probably better if you (being me in this case) are not familiar with Docker Containers.  I've also read that Docker doesn't work well using Ubuntu 24.04.  So I stuck with Python.  I go through the menu,..  I choose Skills, Extra Skills, and GUI and confirm everything is correct.  It then goes through a lot of installing / setup and stops.
I'm adding the ovos-installer.log file.  There's an error in the ansible setup, but seemed odd that this falls over so far later in the piece.  
Am I doing something wrong?? Or is Ubuntu 24.04 the problem??  
I had OVOS working on this same laptop using KUbuntu 22.04 until I rebuilt the laptop.  A) Because I got a message saying that 22.04 wasn't supported anymore, and B) I wanted to see if I could get the OVOS working a bit better than I had it.  
Thanks for the help.
Bryan

[ovos-installer-log-202408232344.txt](https://github.com/user-attachments/files/16729910/ovos-installer-log-202408232344.txt)

**Comment by goldyfruit** [comment]
I was able to replicate the issue, I gonna work on a fix.

**Comment by goldyfruit** [comment]
Fixed with https://github.com/OpenVoiceOS/ovos-installer/commit/4ee11043565f24e632da639ef1b61b33418b1957

**Comment by unstuckconsortium** [comment]
Thanks @goldyfruit I'll give it a go today.  Appreciate your help.

**Comment by unstuckconsortium** [comment]
@goldyfruit I can confirm that the installer worked Successfully.  Thanks for the help. Really appreciate it.

**Comment by goldyfruit** [comment]
Thanks for testing :+1:
