### ISSUE TITLE
Not all icons are visible

### ISSUE THREAD

**Issue by builderjer** [OpenVoiceOS/ovos-installer#134]
I noticed that when I swipe down and use the shutdown/restart button, the icons are not visible.

I think it is missing the `breeze-icon-theme` package. I had to add it to the raspOVOS images for the icons to appear also.
https://github.com/OpenVoiceOS/raspOVOS/blob/49f24be9ed8a65c9466a7d01cea3c6a432c188ce/stage-gui/01-install-packages/01-packages#L23

**Comment by goldyfruit** [comment]
Indeed, nice catch!
