### ISSUE TITLE
ansible check break install on Debian 13

### ISSUE THREAD

**Issue by denics** [OpenVoiceOS/ovos-installer#141]
the command ``ansible localhost -m ansible.builtin.setup | grep distribution_major`` results in ``N/A`` in Debian 13 and break control check in https://github.com/OpenVoiceOS/ovos-installer/blob/main/ansible/site.yml#L27 and https://github.com/OpenVoiceOS/ovos-installer/blob/main/ansible/site.yml#L34.

**Comment by goldyfruit** [comment]
Debian 13 is not stable and will not be supported by the installer until then.
[Someone](https://github.com/OpenVoiceOS/ovos-installer/issues/114) had the issue couple months ago.
