### ISSUE TITLE
update doc installtion

### ISSUE THREAD

**Issue by Vincenzoferrara** [OpenVoiceOS/ovos-installer#149]
when i tried to install this software on a minimal debian distribution i had problems.

the doc says to have already installed `curl, git, sudo` but to launch it i also needed `python3` (i installed `python3 python3-pip python3-venv`) i don't know exactly which ones i needed because i needed them for other things too, but with these listings it was successful

**Comment by goldyfruit** [comment]
Required python packages are automatically installed by the `ovos-installer`.

https://github.com/OpenVoiceOS/ovos-installer/blob/main/utils/common.sh#L199-L232

**Comment by goldyfruit** [comment]
Closing for now, feel free to re-open if needed.
