### ISSUE TITLE
`libjpeg-dev` is needed as a dependency on Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by abraha2d** [OpenVoiceOS/ovos-installer#150]
Hi,

Attempting to install OVOS on a relatively fresh install of Ubuntu 24.04 LTS... I needed to manually install `libjpeg-dev` before the installation would succeed. Without that package, `pillow` was failing to build:

```
      The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.
```

Logs that the installer asked me to share: https://dpaste.com/5WB93DATC

**Comment by goldyfruit** [comment]
Thanks for reporting the issue :+1: 

This is now fixed.
