### ISSUE TITLE
Issue with installer and ReSpeaker 2 mic hat

### ISSUE THREAD

**Issue by RichB-1** [OpenVoiceOS/ovos-installer#154]
Hey all, 

I'm having an issue using OVOS with the ReSpeaker 2 mic hat. When I try the installer file, it works for a bit, until it gets to 'scan i2c bus for hardware auto-detection' - fail, unable to continue the process...Please share this URL with us: https://dpaste.com/H869MH62L

**Comment by goldyfruit** [comment]
@RichB-1 could you please run the `ovos-installer` in DEBUG mode please?

```
sh -c "curl -s https://raw.githubusercontent.com/OpenVoiceOS/ovos-installer/main/installer.sh -o installer.sh && chmod +x installer.sh && sudo ./installer.sh -d && rm installer.sh"
```

**Comment by RichB-1** [comment]
This is the URL that comes up: https://dpaste.com/A32NSXTQJ

**Comment by goldyfruit** [comment]
`dtparam -v i2c_arm=on` seems to be the culprit.

- Which Raspberry Pi model?
- Which Linux distribution on your Raspberry Pi?

**Comment by RichB-1** [comment]
Raspberry Pi 5, 8GB, and Raspberry Pi OS x64 (newest version)

**Comment by goldyfruit** [comment]
> Raspberry Pi 5, 8GB, and Raspberry Pi OS x64 (newest version)

I'm not able to replicate on my RPi 5B 8G with Raspberry Pi OS Bookworm Lite 64-bit.

```
+ i2c_scan
+ '[' 'Raspberry Pi 5 Model B Rev 1.0' '!=' N/A ']'
+ echo -ne '➤ Scan I2C bus for hardware auto-detection...'
➤ Scan I2C bus for hardware auto-detection...+ dtparam -l
+ grep -q i2c_arm=on
+ dtparam -v i2c_arm=on
+ lsmod
+ grep -q i2c_dev
+ modprobe -v i2c-dev
+ for device in "${!SUPPORTED_DEVICES[@]}"
+ address=2f
+ i2c_get 2f
+ i2cdetect -y -a 1 0x2f 0x2f
+ grep -Eq '2f|UU'
+ return 1
+ for device in "${!SUPPORTED_DEVICES[@]}"
+ address=04
+ i2c_get 04
+ i2cdetect -y -a 1 0x04 0x04
+ grep -Eq '04|UU'
+ return 1
+ for device in "${!SUPPORTED_DEVICES[@]}"
+ address=1a
+ i2c_get 1a
+ i2cdetect -y -a 1 0x1a 0x1a
+ grep -Eq '1a|UU'
+ return 1
+ echo -e '[\e[32mdone\e[0m]'
[done]
```

**Comment by goldyfruit** [comment]
> dtparam -v i2c_arm=on

Could you please run this  command manually:

```
sudo dtparam -v i2c_arm=on
```

**Comment by RichB-1** [comment]
This is the output. Will I need to reflash the OS with Lite rather than regular?

https://dpaste.com/3LQSSWSY

**Comment by goldyfruit** [comment]
> This is the output. Will I need to reflash the OS with Lite rather than regular? A few months ago, installing on regular worked
It should not change anything but why not :stuck_out_tongue: Try as well without the HAT.

> https://dpaste.com/3LQSSWSY

The link doesn't work.

**Comment by RichB-1** [comment]
Apologies, mistyped it: https://dpaste.com/3LQSSLWSY

That should work now

**Comment by goldyfruit** [comment]
> Apologies, mistyped it: https://dpaste.com/3LQSSLWSY
> 
> That should work now

Output looks good.

**Comment by RichB-1** [comment]
So should I reflash the OS onto the SD and start fresh? I installed the ReSpeaker drivers from HinTak before installing OVOS, should I have done it the other way round?

Just wondering why the error is coming up

**Comment by goldyfruit** [comment]
> So should I reflash the OS onto the SD and start fresh?

You could try.

> I installed the ReSpeaker drivers from HinTak before installing OVOS, should I have done it the other way round?

No, installing the ReSpeaker module first is the right thing to do.

> Just wondering why the error is coming up

Me too.

**Comment by RichB-1** [comment]
For context, I installed the ReSpeaker drivers from here: https://github.com/HinTak/seeed-voicecard

This is due to the ReSpeaker drivers from their github being outdated

**Comment by RichB-1** [comment]
Okay, so, I reflashed my SD with RPiOS Lite, then installed the ReSpeaker driver from HinTak, then ran install_wm8960.sh from ubopod (apparently that fixed an issue with the ReSpeaker driver on RPi 5, but it could be causing this issue here), before running the curl command, which brought up a failure at the exact same point as before, the debug url is here: https://dpaste.com/CF4SD4GFD

**Comment by goldyfruit** [comment]
Is your EEPROM up-to-date?

```
sudo rpi-eeprom-update -a
sudo reboot
```

**Comment by RichB-1** [comment]
Yeah, it's up to date.

Also, when I rebooted after running the install_wm8960/.sh script, it fails to start the wm8960-soundcard.service - unsure why

**Comment by goldyfruit** [comment]
After a reboot, can you run `sudo dtparam -l`?

**Comment by RichB-1** [comment]
When I run sudo dtparam -v i2c_arm=on, it says '0_dtparam" is already loaded.

When I run sudo dtparam -l, it says that no overlays are loaded

**Comment by goldyfruit** [comment]
> When I run sudo dtparam -v i2c_arm=on, it says '0_dtparam" is already loaded.

Could you please run this again but with the `echo` this time?
```
sudo dtparam -v i2c_arm=on
echo $?
```

**Comment by RichB-1** [comment]
This is the output, having copied that:

1
***@***.***:" $ sudo dtparam -u i2c_arm-on && echo $?
DTOVERLAY [debug]: using platform 'bcm2712'
DTOVERLAY [debug]: overlay map loaded
run_cmd: which dtoverlay-pre >/dev/null 2>&1 && dtoverlay-pre
run_cmd: dtc -I fs -0 dtb -o '/tmp/.dtoverlays/base.dtb' /proc/device-tree 1>/dev/null 2>&1 DTOVERLAY [debug]: loading file '/tmp/.dtoverlays/base.dtb'
DTOVERLAY [debug]: found override i2c_arm
DTOVERLAY [debug]: override i2c_arm: string target 'status'
DTOVERLAY[debug]: wrote 162 bytes to '/tmp/.dtoverlays/0_dtparam.dtbo' * Overlay '0_dtparam' is already loaded
run_cmd: which dtoverlay-post >/dev/null 2>&1 && dtoverlay-post

-------- Original Message --------

**Comment by goldyfruit** [comment]
> This is the output, having copied that: $ sudo dtparam -v i2c_arm=on && echo $? DTOVERLAY [debug]: using platform 'bcm2712' DTOVERLAY [debug]: overlay map loaded run_cmd: which dtoverlay-pre >/dev/null 2>&1 && dtoverlay-pre run_cmd: dtc -I fs -0 dtb -o '/tmp/.dtoverlays/base.dtb' /proc/device-tree 1>/dev/null 2>&1 DTOVERLAY [debug]: loading file '/tmp/.dtoverlays/base.dtb' DTOVERLAY [debug]: found override i2c_arm DTOVERLAY [debug]: override i2c_arm: string target 'status' DTOVERLAY[debug]: wrote 162 bytes to '/tmp/.dtoverlays/0_dtparam.dtbo' * Overlay '0_dtparam' is already loaded run_cmd: which dtoverlay-post >/dev/null 2>&1 && dtoverlay-post

I don't see the output of the `echo`, it should a number `0` if everything is fine.

**Comment by RichB-1** [comment]
Doing 'echo $' or 'echo $?' ?

And I was thinking that too! I'm unsure as to why it wasn't parsed through

Doing echo $? On its own prints 1, not 0. What would the issue here be/what's a fix for it?

Thanks

**Comment by goldyfruit** [comment]
> echo $?

`echo $? `, this return the exit code from the code, `1` means that there is an error and this is why the `ovos-installer` stops!

I gonna check what I can do!

Thanks! :+1:

**Comment by RichB-1** [comment]
Thank you!

**Comment by RichB-1** [comment]
Thank you!

May I ask what microphone and speakers you are using with your setup? I feel I may need to start from scratch with another microphone. Having a look, would the Tonor TC30 be any good?

I'm starting to think that the issue is lying with the drivers for the microphone, so maybe switching to another microphone will work

Thanks for all the help

The reason why I'm asking is that I'm doing a project making a voice assistant and I'm presenting it, so as long as I can get it working, that's all that matters.

Could you advise as to my next steps? Thank you for your help so far

**Comment by goldyfruit** [comment]
> Thank you! May I ask what microphone and speakers you are using with your setup?

I got multiple microphones; I would recommend this one, not the best but works decently https://a.co/d/bvLYplN

> Could you advise as to my next steps? Thank you for your help so far

I'm looking into the issue.

**Comment by goldyfruit** [comment]
Did you see this issue https://github.com/HinTak/seeed-voicecard/issues/19#issuecomment-1879387637 ?

**Comment by RichB-1** [comment]
Thank you,

I'm from the UK, can that product be bought on Amazon UK?

**Comment by JarbasAl** [comment]
@j1nx are respeaker drivers even needed? havet you been recommending everyone to NOT use them?

**Comment by RichB-1** [comment]
Yes I did, I used the alternate install.sh (wm8960) but it hasn't worked thus far

**Comment by goldyfruit** [comment]
Actually I got a ReSpeaker 2 HAT from Seeed Studio... I'm gonna check if it works for me.

**Comment by RichB-1** [comment]
Thank you for all of your help, Gaëtan

**Comment by RichB-1** [comment]
Thank you! If you get it working, please let me know what you had to do

**Comment by goldyfruit** [comment]
Its working for me.

```
$ curl https://raw.githubusercontent.com/ubopod/ubo_app/main/ubo_app/system/install_wm8960.sh | sudo bash
$ sudo reboot
```

Then check for microphone and speakers:
```
$ arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: wm8960soundcard [wm8960-soundcard], device 0: 1f000a0000.i2s-wm8960-hifi wm8960-hifi-0 [1f000a0000.i2s-wm8960-hifi wm8960-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: wm8960soundcard [wm8960-soundcard], device 0: 1f000a0000.i2s-wm8960-hifi wm8960-hifi-0 [1f000a0000.i2s-wm8960-hifi wm8960-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: vc4hdmi0 [vc4-hdmi-0], device 0: MAI PCM i2s-hifi-0 [MAI PCM i2s-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: vc4hdmi1 [vc4-hdmi-1], device 0: MAI PCM i2s-hifi-0 [MAI PCM i2s-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

Running the `ovos-installer` works fine.

**Comment by RichB-1** [comment]
Thank you!

I'll try that tomorrow - I was using wget rather than curl so that explains the potential issue.

So, to be clear, first, update everything, then install the drivers from HinTak, before installing the wm8960 drivers and then rebooting.

After that, use aplay/arecord to double check, and use the ovos-installer.

For reference, what version of Bookworm are you using, Lite or Full?

Thank you so much for everything, I'll try doing it tomorrow and if I have any other issues I'll let you know

**Comment by goldyfruit** [comment]
> I was using wget rather than curl so that explains the potential issue.

Gonna be the same, I'm just not using https://github.com/HinTak/seeed-voicecard as it doesn't seem to work with RPi 5B.

> So, to be clear, first, update everything, then install the drivers from HinTak, before installing the wm8960 drivers and then rebooting. 

Don't used https://github.com/HinTak/seeed-voicecard, use the link from my previous message.

> After that, use aplay/arecord to double check, and use the ovos-installer.

Yes.

> For reference, what version of Bookworm are you using, Lite or Full?

Lite.

> Thank you so much for everything, I'll try doing it tomorrow and if I have any other issues I'll let you know

No problem!

**Comment by RichB-1** [comment]
Ohhh okay, so just use the wm8960 drivers rather than the HinTak ones?

Have you tested the microphone out to see if it works? (Just double checking)

**Comment by goldyfruit** [comment]
> Ohhh okay, so just use the wm8960 drivers rather than the HinTak ones?
Yeah, two different repositories.

> Have you tested the microphone out to see if it works? (Just double checking)

I'm in the process of doing that, running the `ovos-installer` just after a Raspberry Pi OS fresh install.

**Comment by goldyfruit** [comment]
Yes, wake word is picked up.

```
Sep 19 18:29:46 rpi5b ovos-dinkum-listener[22953]: 2024-09-19 18:29:46.222 - voice - ovos_dinkum_listener.voice_loop.voice_loop:start:177 - INFO - Listening mode: ListeningMode.WAKEWORD
Sep 19 18:29:46 rpi5b ovos-dinkum-listener[22953]: 2024-09-19 18:29:46.224 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:203 - INFO - Starting loop in mode: ListeningMode.WAKEWORD
Sep 19 18:29:46 rpi5b ovos-dinkum-listener[22953]: 2024-09-19 18:29:46.224 - voice - ovos_dinkum_listener.service:on_ready:90 - INFO - DinkumVoiceService is ready.
Sep 19 18:29:46 rpi5b ovos-dinkum-listener[22953]: 2024-09-19 18:29:46.226 - voice - ovos_dinkum_listener.service:reload_configuration:1107 - INFO - Reload Completed
Sep 19 18:29:46 rpi5b ovos-dinkum-listener[22953]: 2024-09-19 18:29:46.228 - voice - ovos_config.config:_on_file_change:311 - INFO - /home/goldyfruit/.config/mycroft/mycroft.conf unchanged
Sep 19 18:30:41 rpi5b ovos-dinkum-listener[22953]: 2024-09-19 18:30:41.925 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:234 - INFO - Wakeword detected
Sep 19 18:30:44 rpi5b ovos-dinkum-listener[22953]: 2024-09-19 18:30:44.733 - voice - ovos_dinkum_listener.voice_loop.voice_loop:run:268 - INFO - speech finished
```

**Comment by RichB-1** [comment]
Absolutely perfect, thank you!!

So from this point, if there are any issues, it must be hardware, and at that point, I'll get a new microphone.

**Comment by j1nx** [comment]
> @j1nx are respeaker drivers even needed? havet you been recommending everyone to NOT use them?

Indeed , the wm8960 is included in the default rpi linux kernel. Just load the dtoverlay from the kernel and it works. No need to install different module driver from seeed or hintak.

for the 2mic that is, the 4 and 6 mic need the hintak driver.

**Comment by RichB-1** [comment]
So, to be clear, I just need to run the ovos-installer on a fresh install?

**Comment by j1nx** [comment]
> So, to be clear, I just need to run the ovos-installer on a fresh install?

If I understand the above correctly, you are best to add the dtoverlay=wm8960 (check official names as I do this out the top of my head) to config.txt and reboot first before you run the installer.

**Comment by RichB-1** [comment]
> Its working for me.
> 
> ```
> $ curl https://raw.githubusercontent.com/ubopod/ubo_app/main/ubo_app/system/install_wm8960.sh | sudo bash
> $ sudo reboot
> ```
> 
> Then check for microphone and speakers:
> 
> ```
> $ arecord -l
> **** List of CAPTURE Hardware Devices ****
> card 0: wm8960soundcard [wm8960-soundcard], device 0: 1f000a0000.i2s-wm8960-hifi wm8960-hifi-0 [1f000a0000.i2s-wm8960-hifi wm8960-hifi-0]
>   Subdevices: 1/1
>   Subdevice #0: subdevice #0
> 
> $ aplay -l
> **** List of PLAYBACK Hardware Devices ****
> card 0: wm8960soundcard [wm8960-soundcard], device 0: 1f000a0000.i2s-wm8960-hifi wm8960-hifi-0 [1f000a0000.i2s-wm8960-hifi wm8960-hifi-0]
>   Subdevices: 1/1
>   Subdevice #0: subdevice #0
> card 1: vc4hdmi0 [vc4-hdmi-0], device 0: MAI PCM i2s-hifi-0 [MAI PCM i2s-hifi-0]
>   Subdevices: 1/1
>   Subdevice #0: subdevice #0
> card 2: vc4hdmi1 [vc4-hdmi-1], device 0: MAI PCM i2s-hifi-0 [MAI PCM i2s-hifi-0]
>   Subdevices: 1/1
>   Subdevice #0: subdevice #0
> ```
> 
> Running the `ovos-installer` works fine.

With running the wm8960 installer then rebooting, the wm8960 service fails

**Comment by goldyfruit** [comment]
> With running the wm8960 installer then rebooting, the wm8960 service fails

Failing for me as well but not an issue apparently.

**Comment by RichB-1** [comment]
> > With running the wm8960 installer then rebooting, the wm8960 service fails
> 
> Failing for me as well but not an issue apparently.

Mhm okay, for some reason it isn't hearing me, I've gone into alsamixer and boosted the input as much as I can, and nothing happens - it heard me say 'hey, mycroft' a couple of times but didn't understand what I said after that. 

Should I not have used alsamixer and used pulseaudio instead? Also, did you have to change the mycroft.conf file or not? Just wondering

**Comment by RichB-1** [comment]
> > So, to be clear, I just need to run the ovos-installer on a fresh install?
> 
> If I understand the above correctly, you are best to add the dtoverlay=wm8960 (check official names as I do this out the top of my head) to config.txt and reboot first before you run the installer.

Just doing this results in the 2 mic HAT not even being recognised by arecord -l - I am yet to run the ovos-installer

For reference, I have 2 SD cards and am trying both approaches on each

**Comment by goldyfruit** [comment]
> Okay, so, ovos itself runs through the cli, it's just the stt that is having trouble

What does `wpctl status` says?

**Comment by j1nx** [comment]
The default settings of the wm8960 are not optimal. It needs some amixer settings changes. Have a look at the amixer commands block at this file;

https://github.com/OpenVoiceOS/ovos-buildroot/blob/develop/buildroot-external/board/ovos/raspberrypi/rootfs-overlay/usr/libexec/ovos-i2csound#L96

**Comment by RichB-1** [comment]
So where would I put the amuxet command block?

Thanks

**Comment by RichB-1** [comment]
Also, I'm running into an issue. For some reason I can't install skills. Any fixes?

Thank you!

**Comment by RichB-1** [comment]
It comes out with a lot - the two sources are built in audio stereo and usb audio mono

**Comment by goldyfruit** [comment]
@RichB-1 please join our Matrix chat platform to get some help on the ReSpeaker Mic 2 HAT as this out of scope of the `ovos-installer`. :smiley_cat: 

https://matrix.to/#/!XFpdtmgyCoPDxOMPpH:matrix.org?via=matrix.org
