### ISSUE TITLE
add catalan to language selection

### ISSUE THREAD

**Issue by JarbasAl** [OpenVoiceOS/ovos-installer#158]

**Comment by goldyfruit** [comment]
What is the ISO code fot Catalan?

**Comment by JarbasAl** [comment]
`ca-ES`

**Comment by goldyfruit** [comment]
There is no Catalan translation available https://github.com/OpenVoiceOS/ovos-installer/tree/main/tui/locales

**Comment by goldyfruit** [comment]
https://github.com/OpenVoiceOS/ovos-installer/commit/a1610fe2bde9577d9cb866bdd855041f7f8ad37a
