### ISSUE TITLE
Enable 'Fake barge in' by default?

### ISSUE THREAD

**Issue by timonvanhasselt** [OpenVoiceOS/ovos-installer#169]
Based on a DM with @JarbasAl, maybe a consideration to enable "fake barge in" by default in the user mycroft.conf for RPi users and/or other setups with less quality microphones.

Background: I had a problem where my utterance was not picked up because of the audio/speech that was already playing (setup: PC with jabra speaker). Fake barge in solved that issue for me. I think it's a better UX with fake barge in enabled. 

```
  "listener": {
     "fake_barge_in": true
```

**Comment by goldyfruit** [comment]
Maybe this should be set by default in `ovos-config` rather than in the `ovos-installer`?

**Comment by goldyfruit** [comment]
> mk2 drivers work there should be an exception as the sj201 does noise cancellation at hardware level

This doesn't work since kernel 5.x.

> https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Modules/#module-echo-cancel

PulseAudio is replaced by PipeWire in most of the distributions. PipeWire is only installed and configured by the installer on Raspberry Pi boards as on laptops/PCs the user might have custom settings already configured.

**Comment by goldyfruit** [comment]
> i assume pipewire has an equivalent plugin?

Not that I'm aware off :disappointed:
