### ISSUE TITLE
Request: hivemind bridges

### ISSUE THREAD

**Issue by JarbasAl** [OpenVoiceOS/ovos-installer#20]
an option to install DeltaChat and Matrix hivemind bridges would be nice, these are decentralized open services that safely expose a OVOS instance to be accessed over the web, an easy way to give users access to their devices on the go without complicated setups of VPNs and the likes

-  https://jarbashivemind.github.io/HiveMind-community-docs/09_matrix/
-  https://jarbashivemind.github.io/HiveMind-community-docs/10_deltachat/

**Comment by goldyfruit** [comment]
On pause until https://github.com/JarbasHiveMind/HiveMind-core/issues/78

**Comment by goldyfruit** [comment]
This should be part of the installer dedicated to HiveMind.
