### ISSUE TITLE
[HiveMind] redefining profiles - new hivemind-listener repo

### ISSUE THREAD

**Issue by JarbasAl** [OpenVoiceOS/ovos-installer#200]
When building your HiveMind servers there are many ways to go about it, with many optional components

Common setups:

- **OVOS Device**, a full OVOS install without hivemind
- **Hivemind Skills Server**, a minimal HiveMind server that satellites can connect to, supports **text** utterances
  only
- **Hivemind Sound Server**, a HiveMind server that supports **text** utterances and **streaming audio**
- **Hivemind Persona Server**, exposes a `ovos-persona` (eg. an LLM) that satellites can connect to, without
  running `ovos-core`.

The table below illustrates the most common setups for a OVOS based Mind, each column represents a running OVOS/HiveMind
service on your server

|                             | **hivemind-core** | **hivemind-listener** | **ovos-core** | **ovos-audio** | **ovos-listener** | **hivemind-persona** |
|-----------------------------|-------------------|-----------------------|---------------|----------------|-------------------|----------------------|
| **OVOS Device**             | ❌                 | ❌                     | ✔️            | ✔️             | ✔️                | ❌                    | 
| **Hivemind Skills Server**  | ✔️                | ❌                     | ✔️            | ❌              | ❌                 | ❌                    | 
| **Hivemind Sound Server**   | ❌                 | ✔️                    | ✔️            | ❌              | ❌                 | ❌                    | 
| **Hivemind Persona Server** | ❌                 | ❌                     | ❌             | ❌              | ❌                 | ✔️                   | 

The table below indicates compatibility for each of the setups described above with the most common voice satellites,
each column corresponds to a different satellite

|                             | **voice satellite** | **voice relay** | **mic satellite** |
|-----------------------------|---------------------|-----------------|-------------------|
| **OVOS Device**             | ❌                   | ❌               | ❌                 |
| **Hivemind Skills Server**  | ✔️                  | ❌               | ❌                 |
| **Hivemind Sound Server**   | ✔️                  | ✔️              | ✔️                |
| **Hivemind Persona Server** | ✔️                  | ❌               | ❌                 |

| Feature                          | **HiveMind Voice Satellite**                                      | **HiveMind Voice Relay**                                           | **HiveMind Microphone Satellite**                             |
|-----------------------------------|-------------------------------------------------------------------|-------------------------------------------------------------------|---------------------------------------------------------------|
| **Use Case**                      | Full voice satellite with local processing                        | Offloads voice processing to **HiveMind Listener**, better suited for secure environments | Super lightweight satellite for remote audio streaming       |
| **Audio Processing**              | Local (STT, TTS, Wake Word, VAD)                                  | STT and TTS handled on **HiveMind Listener**                       | Wake Word, STT and TTS handled on **HiveMind Listener**            |
| **Server Requirements**           | Requires only **hivemind-core**                                   | Requires **hivemind-listener**                                     | Requires **hivemind-listener**                                |
| **Voice Activity Detection (VAD)**| Handled locally                                                   | Handled locally                                                    | Handled locally                                               |
| **Wake Word Detection**           | Handled locally                                                   | Handled locally                                   | Handled by **HiveMind Listener**                              |
| **STT Processing**                | Handled locally                                                   | Handled by **HiveMind Listener**                                   | Handled by **HiveMind Listener**                              |
| **TTS Processing**                | Handled locally                                                   | Handled by **HiveMind Listener**                                   | Handled by **HiveMind Listener**                               |

**Comment by goldyfruit** [comment]
I would go with the simplest combination and not try to provide many profiles for HiveMind / OVOS setup as the goal of the installer is to get people started with OVOS / HiveMind.

The installer should remain a simple thing to use.

**Comment by JarbasAl** [comment]
i think currently listener/server profile are confusing, listener profile should use hivemind-listener as described above IMHO

adding more profiles is up to you, just wanted to leave all the info for reference

**Comment by goldyfruit** [comment]
I think HiveMind should be removed from the `ovos-installer` as its getting bigger and more complex.

**Comment by goldyfruit** [comment]
Agree.
