### ISSUE TITLE
Operating System Not Supported: Arch Linux ARM

### ISSUE THREAD

**Issue by 2q2code** [OpenVoiceOS/ovos-installer#202]
Honestly I don't mind if it's supported or not, but there's no linked documentation on how to perform a manual installation if the automated one fails. I will have a look around later on to see if I can find documentation elsewhere or I'll deconstruct the installer script. Just wanted to report this.

The system is a Raspberry Pi 2B+ running Arch Linux ARM. I just want to set it up as a satellite for the main system, which will be a docker container running on an AMD64 server running Arch Linux.

**Comment by goldyfruit** [comment]
Its mentioned [here](https://community.openconversational.ai/t/howto-begin-your-open-voice-os-journey-with-the-ovos-installer/14900), this link is in the `README.md`.

Raspberry Pi 2B+ is 32-bit architecture which is not supported by the installer.

**Comment by 2q2code** [comment]
Okay. Thank you. I skimmed through the whole thread, but was unable to find an answer on this. Is the Pi 2B+ 32-bit architecture not supported, even as a satellite? I just need to know to adjust my aims/hardware etc.

**Comment by goldyfruit** [comment]
> Okay. Thank you. I skimmed through the whole thread, but was unable to find an answer on this. Is the Pi 2B+ 32-bit architecture not supported, even as a satellite? I just need to know to adjust my aims/hardware etc.

From the link above:

![image](https://github.com/user-attachments/assets/3b650ea9-7a93-43d1-96e0-90fe7cd9d223)

**Comment by 2q2code** [comment]
Sorry. This doesn't answer my question. The context around that image says: "Here is a quick overview of what the ovos-installer could provide."

Vague language choices aside, the subject of the graphic is the installer, and not the OVOS in entirety. 

My question is specifically this:

If I were to install OVOS *manually*, will it be able to run as a low-power satellite on a Raspberry Pi 2B+ running Arch Linux ARM?

I mean, an ESP8266 can be made to work as a satellite by turning it into a streaming UDP microphone/speaker pair. All the processing is done on other hardware. So it's not much of a reach to ask if the 2B could run as a satellite. 

It has done so quite well with Rhasspy for years. 

Perhaps I could rephrase again. Is there _anything_, in the satellite mode of OVOS, that _explicitly_ requires a 64-bit architecture?

**Comment by JarbasAl** [comment]
The silero vad plugin won't work in 32bit, wake words with tensor flow might also cause issues, you can always change those plugins that don't work as ovos is super modular, but you are on your own to figure out what even needs changing, in short noone bothered trying to run in 32bit for a long long time

**Comment by 2q2code** [comment]
Fair. Thanks.

**Comment by JarbasAl** [comment]
if you get it working please document your experiences :)

**Comment by goldyfruit** [comment]
> If I were to install OVOS _manually_, will it be able to run as a low-power satellite on a Raspberry Pi 2B+ running Arch Linux ARM?

Did that last year on a Raspberry Pi Zero and I would not recommend it.

**Comment by JarbasAl** [comment]
related to #200 , i think this issue should be closed and considered in the upcoming hivemind-installer, there it makes sense to support the mic satellite, but for OVOS i don't think it makes much sense to explicitly support 32bit in general

**Comment by goldyfruit** [comment]
I do not recommend 32-bit support from us as it might be very hard to guaranty stability and security.

**Comment by goldyfruit** [comment]
Update to be more explicit.

![image](https://github.com/user-attachments/assets/181c9616-857c-4590-864a-8405353a9d85)

**Comment by 2q2code** [comment]
I've updated my minimalist strategy to use the RPi Zero 2 Wireless, which has a 64-bit SOC, same as the 3B, just a fraction slower. Again, just for the satellite mode. The main node is an old gaming PC with plenty of power.

**Comment by goldyfruit** [comment]
> I've updated my minimalist strategy to use the RPi Zero 2 Wireless, which has a 64-bit SOC, same as the 3B, just a fraction slower. Again, just for the satellite mode. The main node is an old gaming PC with plenty of power.

This is the setup I tested. :+1:
