### ISSUE TITLE
Doesn't recognize KDE Neon as Ubuntu

### ISSUE THREAD

**Issue by clintonthegeek** [OpenVoiceOS/ovos-installer#204]
Heyo! I'm running [KDE Neon User Edition](https://neon.kde.org/), which is just Ubuntu's latest LTS release ([24.04 Noble](https://blog.neon.kde.org/2024/10/10/kde-neon-rebased-on-ubuntu-24-04-lts/)—the FAQ is not up to date).

The install-script returns with an error saying that my distro isn't supported, but I assume that [this function](https://github.com/OpenVoiceOS/ovos-installer/blob/84ce283b161771a5bbc0e7459cff0742120ae245/utils/common.sh#L219) could be updated with the appropriate string ("neon") without a problem.

Here is what my `/etc/os-release` looks like:
```
PRETTY_NAME="KDE neon 6.2"
NAME="KDE neon"
VERSION_ID="24.04"
VERSION="6.2"
VERSION_CODENAME=noble
ID=neon
ID_LIKE="ubuntu debian"
HOME_URL="https://neon.kde.org/"
SUPPORT_URL="https://neon.kde.org/"
BUG_REPORT_URL="https://bugs.kde.org/"
PRIVACY_POLICY_URL="https://kde.org/privacypolicy/"
UBUNTU_CODENAME=noble
LOGO=start-here-kde-neon
```
I hacked it to look more like Ubuntu in order to get the install script to work, and it seems to be just fine.

**Comment by goldyfruit** [comment]
Thanks @clintonthegeek for letting me know!
It should be fixed.
