### ISSUE TITLE
mk2 - kdeconnect

### ISSUE THREAD

**Issue by JarbasAl** [OpenVoiceOS/ovos-installer#208]
a system service should be made to run the kdeconnect daemon, for EGLFS we need to pass `--platform offscreen`

```
[Unit]
Description=Connect your OVOS-Device to your smartphone or tablet
After=network-online.target
After=dbus.service

[Service]
ExecStart=/usr/lib/aarch64-linux-gnu/libexec/kdeconnectd --platform offscreen
BusName=org.kde.kdeconnect

[Install]
WantedBy=default.target
```

**Comment by goldyfruit** [comment]
Counterpart should be done as well in `ovos-docker`.

**Comment by goldyfruit** [comment]
Mark II support is gonna be handled by raspOVOS in a near future, no more development will be made for Mycroft devices.
