### ISSUE TITLE
Request: option for GGWave

### ISSUE THREAD

**Issue by JarbasAl** [OpenVoiceOS/ovos-installer#21]
https://github.com/OpenVoiceOS/ovos-audio-transformer-plugin-ggwave  installed in the listener

would enable seamless integration for installing skills over audio, the goal is to integrate this with appstores in the future

message bus spec: https://openvoiceos.github.io/message_spec/ggwave/

**Comment by goldyfruit** [comment]
First part for containers https://github.com/OpenVoiceOS/ovos-docker/commit/93c632e0c615444649f61af225ecaa903990b58e

**Comment by goldyfruit** [comment]
https://github.com/OpenVoiceOS/ovos-installer/commit/6a5674567e58c3972fe6f98608bd57df9af000f9
