### ISSUE TITLE
Instalation Error Rasp 4

### ISSUE THREAD

**Issue by Az-Da-Dadz** [OpenVoiceOS/ovos-installer#221]
my apologizes if im missing something, but i keep getting this error when trying to install on a pi 4 

fatal: [127.0.0.1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: '_boot_directory' is undefined. '_boot_directory' is undefined\n\nThe error appears to be in '/home/azz/ovos-installer/ansible/roles/ovos_installer/tasks/tuning/numa.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Enable NUMA for Raspberry Pi 4 & 5\n  ^ here\n"}

https://dpaste.com/DMDYZFQDL

Thanks Guys
its the only error i have encountered so far. 
(newbie)

**Comment by goldyfruit** [comment]
@Az-Da-Dadz Sorry about that, I did a change yesterday and it worked on a Mark II (RPi 4B) but I didn't try on a pure RPi 4B device.

Should be fixed.

**Comment by Az-Da-Dadz** [comment]
> @Az-Da-Dadz Sorry about that, I did a change yesterday and it worked on a Mark II (RPi 4B) but I didn't try on a pure RPi 4B device.
> 
> Should be fixed.

Awesome thanks mate!
All up and running.
Felt like i was going crazy after researching & troubleshooting for hours i could not for the life of me come across that error, anywhere. Until i noticed you  made an edit 17 hours ago than reality hit. Its not me lol. 

Thanks again 🤙🕺😎

**Comment by goldyfruit** [comment]
> Felt like i was going crazy after researching & troubleshooting for hours i could not for the life of me come across that error, anywhere. Until i noticed you made an edit 17 hours ago than reality hit. Its not me lol.

I missed a test but lesson learned :+1: 

Enjoy!
