### ISSUE TITLE
Typo in readme and error with OVO ADMIN PHAL

### ISSUE THREAD

**Issue by corazon008** [OpenVoiceOS/ovos-installer#224]
Hello, 
Today I tried to install OVOS and after running the installer.sh, I ran this commands below 
```shell
systemctl --user list-units "*ovos*"
systemctl list-units "*ovos*"
systemctl --user start ovos
sudo systemctl start ovos-phal-admin
```
And here is the result (Yes the admin-phal failed and I don't know why 😭)
![image](https://github.com/user-attachments/assets/a82be80c-6f43-4c0f-b7f5-b189daca91d9)
As you can see on the last version ovos-phal-admin seems to be renamed as ovos-admin-phal

**Comment by corazon008** [comment]
MB It doesn't work neither
![image](https://github.com/user-attachments/assets/3a587743-a7d2-4bbf-a2df-670e76b7ce00)
So I leave it to you guys 😅

**Comment by corazon008** [comment]
After some troubleshooting with GPT here is what he give to me
### **Issue Summary:**

The `ovos-admin-phal.service` is currently placed in the `~/.config/systemd/user/` directory, which makes it a **user-level service** (`--user`). However, according to the official documentation, this service should be executed in the **system context** with `sudo` and should be placed in the `/etc/systemd/system/` directory.

---

### **Solution:**

To resolve this issue and align with the official Open Voice OS documentation, follow these steps:

#### **Step 1: Move the service to the correct directory**
1. Move the `ovos-admin-phal.service` file from `~/.config/systemd/user/` to `/etc/systemd/system/`:
   ```bash
   sudo mv ~/.config/systemd/user/ovos-admin-phal.service /etc/systemd/system/
   ```

2. Reload the systemd daemon to recognize the new service location:
   ```bash
   sudo systemctl daemon-reload
   ```

#### **Step 2: Start the service correctly**
1. Enable the service to start on boot:
   ```bash
   sudo systemctl enable ovos-admin-phal.service
   ```

2. Start the service:
   ```bash
   sudo systemctl start ovos-admin-phal.service
   ```

#### **Step 3: Check the service status**
Verify the status of the service to make sure it is running:
```bash
sudo systemctl status ovos-admin-phal.service
```

---

### **Main Commands After Fix:**

1. **To start Open Voice OS:**
   ```bash
   systemctl --user start ovos
   sudo systemctl start ovos-phal-admin
   ```

2. **To stop Open Voice OS:**
   ```bash
   systemctl --user stop ovos
   sudo systemctl stop ovos-phal-admin
   ```

---

By moving the service to the correct directory (`/etc/systemd/system/`) and using `sudo` to manage the `ovos-phal-admin` service, the issue related to `GROUP` and `Permission not permitted` should be resolved. Let me know if you encounter any issues after this!

**Comment by goldyfruit** [comment]
As described [here](https://github.com/orgs/OpenVoiceOS/discussions/283), `ovos-installer` is not supported on raspOVOS.
