### ISSUE TITLE
Install on server

### ISSUE THREAD

**Issue by corazon008** [OpenVoiceOS/ovos-installer#225]
Hello,
I tried to run the ovos-installer on a x86 server. But I have this error.
[dpaste](https://dpaste.com/6YU4MPL6J)
![image](https://github.com/user-attachments/assets/ccf0d27b-30f3-44ac-8108-a9fd90623410)
![image](https://github.com/user-attachments/assets/08c77c00-5492-4dee-a062-7b3e3c70b0e7)

**Comment by goldyfruit** [comment]
I'm not able to replicate the issue.
Do you have a sound card on your server _(which is not required by the `listener` profile but I'm just wondering)_?

**Comment by goldyfruit** [comment]
> No I don't. ?

Then the `server` profile should be used and not the `listener` one.

**Comment by JarbasAl** [comment]
listener is a server + audio, so you could use it both as standalone device or server

**Comment by goldyfruit** [comment]
`server` profile is meant to run on servers without audio component, like you do.

**Comment by corazon008** [comment]
@goldyfruit 
Sorry but after the installation completed without errors (with the screen telling me to speak to it) I can't find any relevant folder like the `.venv`
![image](https://github.com/user-attachments/assets/8f8f3f84-19b1-49ae-a76e-04deb78249c4)
And in the `satellite` installation it ask me a password however I did not set up any password for the server.

**Comment by goldyfruit** [comment]
@corazon008 

- I think you ran the `ovos-installer` as a `root` user to the `.venvs` directory is gonna be at `/root/.venvs`.
- Before running the `satellite` installation you need to create credentials/client as described [here](https://jarbashivemind.github.io/HiveMind-community-docs/02_create/).
