### ISSUE TITLE
installer breaks off at last step

### ISSUE THREAD

**Issue by bramm98** [OpenVoiceOS/ovos-installer#228]
Hi,

Perhaps a dumb question, but I can't seem to figure it out.  I installed in WSL2 and it breaks off, with every choice I make I've created a wsl.conff in /etc but wsl doens;t use systemd so I'm not sure how to get this to work anyway.Same happens on the raspberyy pi 5. I've looked at a few different assistants but OPenVoiceOS fits the best to my needs. What can be the reason the installer just stops and doesn't do anyting then displaying the prompt again?

I've ran the docker image succesfully, but since my speakers and microphone are not here yet, I would like to try and talk to the assistant inside a text chat.
but with the cli I don't see anything happening

Could anyone give me an insight on both of my issues?

Thanks

Bram

**Comment by goldyfruit** [comment]
Make sure you select `Yes` at the last screen.

**Comment by goldyfruit** [comment]
Please re-open if needed.
