### ISSUE TITLE
Request: Voice Selection

### ISSUE THREAD

**Issue by JarbasAl** [OpenVoiceOS/ovos-installer#30]
continuing https://github.com/OpenVoiceOS/ovos-installer/issues/23

different voices options could be provided as part of advanced configuration

a default voice per language should also be selected by the community to be used

**Comment by goldyfruit** [comment]
> a default voice per language should also be selected by the community to be used

This is already done here https://github.com/OpenVoiceOS/ovos-installer/blob/main/ansible/roles/ovos_installer/templates/mycroft.conf.j2#L68-L87

**Comment by goldyfruit** [comment]
Solved by https://github.com/OpenVoiceOS/lang_configs
