### ISSUE TITLE
Can't install on WSL Ubuntu 20.04

### ISSUE THREAD

**Issue by HyperUpscale** [OpenVoiceOS/ovos-installer#38]
So I installed python 3.11, so it passed the first problem with the missing 
python3.11 python3.11-dev python3.11-venv

`E: Couldn't find any package by regex python3.11 
E: Couldn't find any package by glob python3.11 
E: Couldn't find any package by regex python3.11-dev 
E: Couldn't find any package by glob python3.11-dev 
E: Couldn't find any package by regex python3.11-venv
E: Couldn't find any package by glob python3.11-venv `
                      

.... 

===============================================
                        OPEN VOICE OS INSTALLER | Version: b376ab73
                      ===============================================

➤ Checking for existing instance... [done]
➤ Retrieving OS information... [done]
➤ Validating WSL2 requirements... [done]
➤ Detecting AVX/SIMD support... [done]
➤ Checking for Raspberry Pi board... [done]
➤ Detecting sound server... [done]
➤ Detecting display server... [done]
➤ Validating installer package requirements... [done]
➤ Creating installer Python virtualenv... [done]
➤ Installing Ansible requirements in Python virtualenv... [done]
**`utils/common.sh: line 268: $YQ_URL/yq_${kernel@L}_$arch: bad substitution`**

user20@WORKSTATION:~$ uname -a
Linux WORKSTATION 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

user20@WORKSTATION:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

**ChatGPT suggests to install separately Docker and Podman**
...

------------------
> /var/log/ovos-installer.log 
/usr/bin/pactl
Hit:1 https://download.docker.com/linux/ubuntu focal InRelease
Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:3 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal InRelease
Get:5 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  InRelease [1642 B]
Hit:6 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:7 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Fetched 1642 B in 1s (1539 B/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
whiptail is already the newest version (0.52.21-4ubuntu2).
expect is already the newest version (5.45.4-2build1).
jq is already the newest version (1.6-1ubuntu0.20.04.1).
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
python3.11 is already the newest version (3.11.7-1+focal1).
python3.11-dev is already the newest version (3.11.7-1+focal1).
python3.11-venv is already the newest version (3.11.7-1+focal1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pip in /home/user20/.venvs/ovos-installer/lib/python3.11/site-packages (23.2.1)
Collecting pip
  Obtaining dependency information for pip from https://files.pythonhosted.org/packages/15/aa/3f4c7bcee2057a76562a5b33ecbd199be08cdb4443a02e26bd2c3cf6fc39/pip-23.3.2-py3-none-any.whl.metadata
  Using cached pip-23.3.2-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: setuptools in /home/user20/.venvs/ovos-installer/lib/python3.11/site-packages (65.5.0)
Collecting setuptools
  Obtaining dependency information for setuptools from https://files.pythonhosted.org/packages/bb/e1/ed2dd0850446b8697ad28d118df885ad04140c64ace06c4bd559f7c8a94f/setuptools-69.0.2-py3-none-any.whl.metadata
  Using cached setuptools-69.0.2-py3-none-any.whl.metadata (6.3 kB)
Using cached pip-23.3.2-py3-none-any.whl (2.1 MB)
Using cached setuptools-69.0.2-py3-none-any.whl (819 kB)
Installing collected packages: setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 65.5.0
    Uninstalling setuptools-65.5.0:
      Successfully uninstalled setuptools-65.5.0
  Attempting uninstall: pip
    Found existing installation: pip 23.2.1
    Uninstalling pip-23.2.1:
      Successfully uninstalled pip-23.2.1
Successfully installed pip-23.3.2 setuptools-69.0.2
Collecting ansible==8.6.1
  Using cached ansible-8.6.1-py3-none-any.whl.metadata (7.9 kB)
Collecting PyYAML==5.3.1
  Using cached PyYAML-5.3.1-cp311-cp311-linux_x86_64.whl
Collecting ansible-core~=2.15.6 (from ansible==8.6.1)
  Using cached ansible_core-2.15.8-py3-none-any.whl.metadata (7.0 kB)
Collecting jinja2>=3.0.0 (from ansible-core~=2.15.6->ansible==8.6.1)
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting cryptography (from ansible-core~=2.15.6->ansible==8.6.1)
  Using cached cryptography-41.0.7-cp37-abi3-manylinux_2_28_x86_64.whl.metadata (5.2 kB)
Collecting packaging (from ansible-core~=2.15.6->ansible==8.6.1)
  Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting resolvelib<1.1.0,>=0.5.3 (from ansible-core~=2.15.6->ansible==8.6.1)
  Using cached resolvelib-1.0.1-py2.py3-none-any.whl (17 kB)
Collecting MarkupSafe>=2.0 (from jinja2>=3.0.0->ansible-core~=2.15.6->ansible==8.6.1)
  Using cached MarkupSafe-2.1.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.0 kB)
Collecting cffi>=1.12 (from cryptography->ansible-core~=2.15.6->ansible==8.6.1)
  Using cached cffi-1.16.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting pycparser (from cffi>=1.12->cryptography->ansible-core~=2.15.6->ansible==8.6.1)
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Using cached ansible-8.6.1-py3-none-any.whl (48.3 MB)
Using cached ansible_core-2.15.8-py3-none-any.whl (2.2 MB)
Using cached cryptography-41.0.7-cp37-abi3-manylinux_2_28_x86_64.whl (4.4 MB)
Using cached packaging-23.2-py3-none-any.whl (53 kB)
Using cached cffi-1.16.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (464 kB)
Using cached MarkupSafe-2.1.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (28 kB)
Installing collected packages: resolvelib, PyYAML, pycparser, packaging, MarkupSafe, jinja2, cffi, cryptography, ansible-core, ansible
Successfully installed MarkupSafe-2.1.3 PyYAML-5.3.1 ansible-8.6.1 ansible-core-2.15.8 cffi-1.16.0 cryptography-41.0.7 jinja2-3.1.2 packaging-23.2 pycparser-2.21 resolvelib-1.0.1
Starting galaxy collection install process
Nothing to do. All requested collections are already installed. If you want to reinstall them, consider using `--force`.
_------------------------

I don't know what would be the easiest fix... ;\

**Comment by goldyfruit** [comment]
Let me try to reproduce your issue.

> 
> **ChatGPT suggests to install separately Docker and Podman** ...
> 

Yeah, I would not trust that much ChatGPT for this type of debugging, the installer only installer Docker, not Podman.

**Comment by goldyfruit** [comment]
I'm not able to reproduce your issue, I removed my WSL2 instance and create a fresh one and I got no trouble with Python packages.

Are you using the scenario?

**Comment by goldyfruit** [comment]
Just tried with scenario as well and I got not issue.

**Comment by goldyfruit** [comment]
Ok, I know why, you are running Ubuntu 20.04 _(Focal)_ on your WSL2, I'm running Ubuntu 22.04 _(Jammy)_ on WSL2.

**Comment by goldyfruit** [comment]
> Ok, I know why, you are running Ubuntu 20.04 _(Focal)_ on your WSL2, I'm running Ubuntu 22.04 _(Jammy)_ on WSL2.

I'm fully able to reproduce your issue on Ubuntu 20.04 after installing Python 3.11 via the `ppa:deadsnakes/ppa` repository.

Let me see if I can find a solution for this "old" release.

**Comment by goldyfruit** [comment]
The issue is related to Bash, Ubuntu 20.04 provides Bash 5.0 and the script uses a feature _(`${XXX@L}`)_ only available from Bash 5.1.

**Comment by goldyfruit** [comment]
Just pushed a fix, let me know if it fixes the issue for you.

**Comment by HyperUpscale** [comment]
WOW 

YES! You fixed everything. Thank you so much!! 

I really appreciate your effort. Now the install is smooth and easy.
