### ISSUE TITLE
Updating box in finish.sh

### ISSUE THREAD

**Issue by unfirthman** [OpenVoiceOS/ovos-installer#54]
Hello!

When finishing an install of `en-us` the whiptail box does not allow the user to view all of the text. Scroll is not available. This is visible via the final screenshot in the readme

I would like to try increasing the height of the whiptail box to include this extra text. I believe the relevant change would be to alter 

`whiptail --msgbox --ok-button "$OK_BUTTON" --title "$TITLE" "$CONTENT" 25 80`

by increasing 25 to 35 like this

`whiptail --msgbox --ok-button "$OK_BUTTON" --title "$TITLE" "$CONTENT" 35 80`

However, I am having trouble configuring a test environment where I can test this change. How does one configure a test environment to check a whiptail box?

I apologize if this is a lot to ask! I figured it would be quicker for me to learn now - or someone can enlighten me on the proper process to help in this way.

Thank you!

**Comment by goldyfruit** [comment]
Fixed, feel free to re-open if not :)
