### ISSUE TITLE
Where are the logs for the docker version?

### ISSUE THREAD

**Issue by aseques** [OpenVoiceOS/ovos-installer#62]
I installed the docker version using the script, apparently everything is working, but the system isn't picking any commands.
Where are the logs located (I am mainly interested in the boot logs for the main daemon and also  a live view of what is ovos receiving.

**Comment by goldyfruit** [comment]
Hi,

There are no boot logs or daemon as you selected Docker as installation method.

To get the logs you will have to run `docker logs` command; https://openvoiceos.github.io/ovos-docker/getting-started/docker/debug/#specific-container-logs

The `ovos_listener` will mostly be the one to check as this is the one listening for the wake word.

```
docker ps -a
docker logs --tail 200 -f ovos_listener
```
