### ISSUE TITLE
[FEATURE] Back button in TUI

### ISSUE THREAD

**Issue by mikejgray** [OpenVoiceOS/ovos-installer#64]
While the TUI menu isn't that long, if you make a mistake you currently have to go all the way to the end, cancel, and start over to fix it. A back button would be great!

**Comment by suvanbanerjee** [comment]
can i work on this issue?

**Comment by goldyfruit** [comment]
> can i work on this issue?

Sure, give it a try. :+1:

**Comment by suvanbanerjee** [comment]
From use point of view i expect a back button on the bottom besides the OK and Cancel buttons.

But however, Whiptail does not provide a way to add a back button. So, i have to create a Back button inside the menu itself.

Check the image below to see how it looks like
![image](https://github.com/OpenVoiceOS/ovos-installer/assets/104707806/56e43a8d-a2ae-4af7-954c-d538104254e3)
If if's ok with you, i will go ahead and implement this feature.

**Comment by goldyfruit** [comment]
> From user's point of view i expect a back button on the bottom of menu besides the OK and Cancel buttons.
> 
> But however, Whiptail does not provide a way to add a back button. So, i have to create a Back button inside the menu itself.
> 
> Check the image below to see how it looks like
> ![image](https://github.com/OpenVoiceOS/ovos-installer/assets/104707806/56e43a8d-a2ae-4af7-954c-d538104254e3)
> If if's ok with you, i will go ahead and implement this feature.

Sure go for it, we can try and adjust if required.
