### ISSUE TITLE
add Uninstall Instructions in README.md

### ISSUE THREAD

**Issue by suvanbanerjee** [OpenVoiceOS/ovos-installer#68]
I think there should be a mention in README.md on how to uninstall ovos also

**Comment by suvanbanerjee** [comment]
@goldyfruit can i work on this issue

**Comment by goldyfruit** [comment]
Sure

**Comment by suvanbanerjee** [comment]
@goldyfruit how about adding a force uninstall in arguments that will bypass the EXISTING_INSTANCE check ?

**Comment by goldyfruit** [comment]
> @goldyfruit how about adding a force uninstall in arguments that will bypass the EXISTING_INSTANCE check ?

Its already the case with the `-u` option.

https://github.com/OpenVoiceOS/ovos-installer/blob/main/utils/argparse.sh#L9
