### ISSUE TITLE
Handle scenario existing file but empty

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-installer#72]
The installer should check if the scenario file contains YAML data as for now an empty scenario file triggers the `ovos-installer` to run non-interactive.

**Comment by suvanbanerjee** [comment]
@goldyfruit Can i work on this issue ?

**Comment by goldyfruit** [comment]
> @goldyfruit Can i work on this issue ?
> 
> I am thinking to create a `validate.sh` file that will use regex to validate the correctness of `config.yaml`

No need to add complexity.

Have a look to the draft https://github.com/OpenVoiceOS/ovos-installer/pull/73, still have to fix the BATS testing.
