### ISSUE TITLE
cant install on ubuntu amd laptop

### ISSUE THREAD

**Issue by coding-garden-1** [OpenVoiceOS/ovos-installer#76]
after running with all defaults, i get

		      ===============================================
		        OPEN VOICE OS INSTALLER | Version: 12aa29e7
		      ===============================================

➤ Checking for existing instance... [done]
➤ Retrieving OS information... [done]
➤ Detecting AVX/SIMD support... [done]
➤ Checking for Raspberry Pi board... [done]
➤ Detecting sound server... [done]
➤ Detecting display server... [done]
➤ Validating installer package requirements... 
[done]
➤ Creating installer Python virtualenv... [done]
➤ Installing Ansible requirements in Python virtualenv... [done]
➤ Looking for automated scenario... [done]
rose@rosebook:~$ 

same for docker/pyvenv

**Comment by goldyfruit** [comment]
Seems you are using the scenario, could you please show me the file?

**Comment by suvanbanerjee** [comment]
@goldyfruit i think there is some issue with the automated scenerio 
![image](https://github.com/OpenVoiceOS/ovos-installer/assets/104707806/b21a8ce1-69ad-4988-9a24-0d8fcc27c38d)
just tried the script using the link in readme and got this. instead of tui

**Comment by coding-garden-1** [comment]
Where do the logs get stored? Not sure where to find

**Comment by suvanbanerjee** [comment]
> Where do the logs get stored? Not sure where to find

Check your `/var/log` directory there you will have a `ovos-installer.log` file

**Comment by goldyfruit** [comment]
Please re-open if required.
