### ISSUE TITLE
OS not supported in Zorin OS

### ISSUE THREAD

**Issue by Vaibhav-Magadum** [OpenVoiceOS/ovos-installer#80]
![image](https://github.com/OpenVoiceOS/ovos-installer/assets/139147981/4895650b-6daf-470e-8695-00d827d0aa0c)

I am using Zorin OS (which is based on ubuntu) which is supported but installer is saying otherwise.

Log:
utils/common.sh: line 117: docker: command not found
utils/common.sh: line 120: podman: command not found
/usr/bin/pactl
Operating system not supported.

My system info 
![image](https://github.com/OpenVoiceOS/ovos-installer/assets/139147981/5afccb92-5d10-42ab-9b60-2efdfde80fa0)

**Comment by suvanbanerjee** [comment]
@goldyfruit i would like to give it a shot

**Comment by goldyfruit** [comment]
@Vaibhav-Magadum Zorin OS is not a supported OS at this time (check the README).

> @goldyfruit i would like to give it a shot

Do you plan to add Zorin OS support?

**Comment by suvanbanerjee** [comment]
> @Vaibhav-Magadum Zorin OS is not a supported OS at this time (check the README).
> 
> > @goldyfruit i would like to give it a shot
> 
> Do you plan to add Zorin OS support?

I am thinking to implement something which can detect base distro or package mgr. because there are many disro apart from zorin that have the same issue ig. thus adding just zorin is not a good solution

**Comment by suvanbanerjee** [comment]
> > I am thinking to implement something which can detect base distro or package mgr. because there are many distro apart from zorin that have the same issue ig (like pop mint etc). thus adding just zorin is not a good solution.
> > zorin should work fine if the installer allows it to install.
> 
> No need to add complexity, Zorin OS is based on Ubuntu, so technically adding `zorinos` _(or whatever it is)_ to https://github.com/OpenVoiceOS/ovos-installer/blob/main/utils/common.sh#L203 should be enough. 🤞

Tried it and not working there is issue with pipewire log - https://sprunge.us/OTCwZZ

**Comment by goldyfruit** [comment]
> > > I am thinking to implement something which can detect base distro or package mgr. because there are many distro apart from zorin that have the same issue ig (like pop mint etc). thus adding just zorin is not a good solution.
> > > zorin should work fine if the installer allows it to install.
> > 
> > 
> > No need to add complexity, Zorin OS is based on Ubuntu, so technically adding `zorinos` _(or whatever it is)_ to https://github.com/OpenVoiceOS/ovos-installer/blob/main/utils/common.sh#L203 should be enough. 🤞
> 
> Tried it and not working there is issue with pipewire log - https://sprunge.us/OTCwZZ

As expected, you will have to fiddle as I did with Linux Mint; https://github.com/OpenVoiceOS/ovos-installer/blob/main/ansible/roles/ovos_installer/tasks/sound.yml#L8

**Comment by suvanbanerjee** [comment]
@goldyfruit tried fiddling with `sound.yaml` it kindof worked but ig it's issue with pip 
log - https://sprunge.us/FgLCUx
can you confirm its issue with pip or installer ?

**Comment by goldyfruit** [comment]
> @goldyfruit tried fiddling with `sound.yaml` it kindof worked but ig it's issue with pip log - https://sprunge.us/FgLCUx can you confirm its issue with pip or installer ?

You are missing a package so you can't build `fann2`.

```
Couldn't find swig2.0 binary!
```

**Comment by goldyfruit** [comment]
@Vaibhav-Magadum the `ovos-installer` should now be able to run on Zorin OS.
Thanks to @suvanbanerjee :+1:
