### ISSUE TITLE
Trouble installing OVOS on DietPi

### ISSUE THREAD

**Issue by twerpyfie** [OpenVoiceOS/ovos-installer#83]
Hay, i've got a RockPi 4B with DietPi. I've trouble installing OVOS on it. Here is the log:

https://sprunge.us/RdkK7e

:>

**Comment by goldyfruit** [comment]
Hi @twerpyfie 

Could you please share the content of `/etc/os-release`?

**Comment by twerpyfie** [comment]
Hi @goldyfruit 


Sure :)

/etc/os-release:

```
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by twerpyfie** [comment]
DietPi does not have  a Desktopenviroment. Maby thats the Problem. I installed Debian 11 with KDE on it and ran into errors too.

https://sprunge.us/56lkM1



```
RETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by goldyfruit** [comment]
Thanks @twerpyfie.

There is no need for Deskstop environment as the OVOS GUI will leverage EGLFS, I would recommend to go without it as well as Debian Bookworm _(12)_ instead of Bullseye _(11)_.

The issue should be fixed by this commit https://github.com/OpenVoiceOS/ovos-installer/commit/149c8051b12abe9aa467a361c5ecc6ad0a2ba0f1

**Comment by twerpyfie** [comment]
Thanks, i will test it later :)

**Comment by goldyfruit** [comment]
Closing for now. Feel free to re-open if the issue still there. :+1:
