### ISSUE TITLE
[DevKit] Touchscreen does not work with default configuration.

### ISSUE THREAD

**Issue by denics** [OpenVoiceOS/ovos-installer#85]
I am using RaspianOS 12 with kernel 6.6.28+rpt-rpi-v8
To enable touchscreen in DevKit I had to comment line 
```
#dtoverlay=vc4-kms-v3d
```
and add line:
```
dtoverlay=vc4-fkms-v3d
```

is this necessary for the Mark2 ? if yes, can we add this to the ansible?

**Comment by goldyfruit** [comment]
Mark II doesn't need `vc4-fkms-v3d` which is good as `vc4-fkms-v3d` _(Fake KMS)_ is getting less attention from the Raspberry Pi developers as their focus is now more for on the Full KMS implementation.

https://github.com/raspberrypi/documentation/issues/2310

**Comment by goldyfruit** [comment]
We could find a way to detect both, DevKit is running version 06 of SJ201 as Mark II is running version 10. If version 06 is detected then we can replace `vc4-kms-v3d` by `vc4-fkms-v3d`.

**Comment by goldyfruit** [comment]
https://github.com/OpenVoiceOS/ovos-installer/pull/86

**Comment by goldyfruit** [comment]
@denics have a look at #86 please and let me know if it works for you.

**Comment by denics** [comment]
ok, I'll try that tomorrow and report back

**Comment by goldyfruit** [comment]
Test and validated by @mikejgray :heart:
