### ISSUE TITLE
Idea/Request: More verbosity / options for the skills section

### ISSUE THREAD

**Issue by j1nx** [OpenVoiceOS/ovos-installer#89]
Following the docker install route at some point you end up with the below screen;
![image](https://github.com/OpenVoiceOS/ovos-installer/assets/641281/3459e7a1-3052-4758-a328-709de7e07f95)

My request / Idea:
Could the skills section be split off from here as a seperate step with the following options
1) Basic/ Default skills
2) Extended skills
3) Advanced/ Manual selected

Option 1 then just do what is does now.
Option 2 basically installs all the by ovos-docker supported skills
Option 3 then just goes to another second skills page which lists all the supported skills at which you can select the ones that you would like to install

Does that make sense?

**Comment by goldyfruit** [comment]
I'm planning to add "Extended skills" but not "Advanced/ Manual selected" as it might be hard to maintained.

**Comment by j1nx** [comment]
No problem. Perhaps when the market place is ready, matures we can always revisit it or otherwise that might make it easier to install.

**Comment by goldyfruit** [comment]
https://github.com/OpenVoiceOS/ovos-installer/pull/92
