### ISSUE TITLE
Auto-detect Mark 1 hardware

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-installer#9]
It would be nice to the installer to detect original Mycroft Mark 1 hardware in order to install the right Open Voice OS requirements and have a Mark 1 working out of the box.

**Comment by JarbasAl** [comment]
related related https://github.com/OpenVoiceOS/ovos-i2csound

ping @j1nx and @builderjer so you can unify efforts

**Comment by goldyfruit** [comment]
https://github.com/OpenVoiceOS/ovos-installer/pull/79
