### ISSUE TITLE
xmodmap missing

### ISSUE THREAD

**Issue by denics** [OpenVoiceOS/ovos-installer#90]
not sure it is worth an issue, but on raspberryOS 12 the installer does not install xmodmap and apparently it is needed. perhaps to add to the requirements? 

```
2024-05-24 23:59:43.895 - PHAL - ovos_phal_plugin_hotkeys.keyboard._nixkeyboard:get_xmod_map:96 - WARNING - [WARNING] xmodmap not available!
```

**Comment by goldyfruit** [comment]
Mostly because of ELGFS, we decided to let the warning just as an information.

https://github.com/OpenVoiceOS/ovos-PHAL-plugin-hotkeys/commit/6be203e02b61901459080a08a8251fc384d49dd9
