### ISSUE TITLE
regarding Arch

### ISSUE THREAD

**Issue by Shadowphoenix** [OpenVoiceOS/ovos-installer#91]
ik Arch is currently unsupported however i think i have found a way to still make it work.

https://aur.archlinux.org/packages/python311 can be used to get the python-venv up and running so i would find it reasonable to at least mention this in the Readme, however with the Caviart of saying that running anything from the AUR means you are on your own.

**Comment by goldyfruit** [comment]
@Shadowphoenix Arch is a supported OS.

**Comment by JarbasAl** [comment]
arch is now on python 3.12, i believe that is the problem here

**Comment by Shadowphoenix** [comment]
> @Shadowphoenix Arch is a supported OS.
> 
> https://github.com/OpenVoiceOS/ovos-installer/blob/main/utils/common.sh#L235
> 

yeah i seem to have had a bit of an Aneurysm skimming the Readme Lol. Yeah, Installer doesnt work with Python 3.12 because the script searches for 3.11 specificall. installing Python 3.11 for example via that AUR-Package is a workaround for the time being

**Comment by goldyfruit** [comment]
I think it might be time to switch to Python 3.12, I gonna have to run more tests but so far so good.

**Comment by goldyfruit** [comment]
@Shadowphoenix do you mind to try this PR https://github.com/OpenVoiceOS/ovos-installer/pull/101?

**Comment by Shadowphoenix** [comment]
> @Shadowphoenix do you mind to try this PR #101?

will do tmrw.

**Comment by Shadowphoenix** [comment]
On another note i suggest rewriting the Readme a little.

Remember how i stumbled over the | Arch | N/A | you have written there? 

Usually when i encounter N/A, it means "not available". This suggests that something is not supported in any way shape or form which was what lead me to think i cant run this on Arch properly. 

https://en.wikipedia.org/wiki/N/A

While technically it is correct as there is no one specific version of Arch you need to run this, this is a bit misleading.
Since Arch, Manjaro and the other rolling releases dont have any specific "versions" that could be supported because they are rolling releases, why not replace the "not available" with "supported" or a simple "Yes"?

**Comment by goldyfruit** [comment]
N/A works as well for Not Applicable but I will have a look on how to improve it.

**Comment by goldyfruit** [comment]
Change got merged, please re-open if needed.

**Comment by goldyfruit** [comment]
https://github.com/OpenVoiceOS/ovos-installer/commit/3c1a3d515eb6ab2ec3e88fb3bdc7e1f453e5551b
