### ISSUE TITLE
install ovos-PHAL-plugin-mk2-v6-fan-control when DevKit is detected

### ISSUE THREAD

**Issue by denics** [OpenVoiceOS/ovos-installer#93]
When installing, if DevKit is detected, ovos-PHAL-plugin-mk2-v6-fan-control should be installed by default

**Comment by goldyfruit** [comment]
I will wait until people test this plugin before doing any work on it :+1:

**Comment by denics** [comment]
with this https://github.com/OpenVoiceOS/ovos-PHAL-plugin-mk2-v6-fan-control/pull/3 I confirm the plugin is working fine on a mk2-v6, better known as the DevKit :)

**Comment by goldyfruit** [comment]
Done https://github.com/OpenVoiceOS/ovos-installer/commit/729a5ee704df5ce735df77f646710ca4eb9902d9
