### ISSUE TITLE
Possible improvement for "features" text

### ISSUE THREAD

**Issue by timonvanhasselt** [OpenVoiceOS/ovos-installer#98]
I think the "feature" text (https://github.com/OpenVoiceOS/ovos-installer/blob/main/tui/locales/en-us/features.sh) is not so clear for new users. 

possible improvements:
* Maybe idea to leave out technical terms like KDE Plasma, Kirigami and Qt? (I know it could be interesting to mention somewhere for some endusers)
* make more clear that GUI is an extra layer next to the voice interaction. It seems a choice between (voice) skills and GUI now, and that's not the case. 
* I know your goal is to leave the option open to install OVOS without the base skills, but maybe that can be made more clear in the text?

Always happy to help with a complete (alternative) text of course.

**Comment by goldyfruit** [comment]
Please @timonvanhasselt feel free to open a PR, I will review it. :+1:
